# Dependencies
markdown:             rdiscount
highlighter:          pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:               FamilyLife.Rocks
tagline:             'parenting in germany'
description:         'A blog about parenting in Germany. Made by <a href="https://twitter.com/meet_lisa" target="_blank">@meet_lisa</a> & <a href="https://twitter.com/potzenheimer" target="_blank">@potzenheimer</a>.'
url:                 http://familylife.rocks
baseurl:             /
paginate:            5

# About/contact
author:
  name:              FamilyLifeRocks
  url:               https://twitter.com/familyrocksblog
  email:             service@familylife.rocks

# Server
destination:      ./_site
exclude:          [".editorconfig", ".gitignore", ".bowerrc", "jshintrc", "bower.json", "config.json", "Gruntfile.js", "package.json", "manifest.cfg", "rules.xml", "node_modules", "bower_components", "README.md", "less", "dist", "js", "overrides", "docs", "templates", "Makefile"]
port:             9001

# Custom vars
current_version:  1.0.0
repo:             https://github.com/ade25/

# prose.io editing setup
prose:
  siteurl: 'http://meetlisa.github.io'
  media: 'assets/img'
  ignore:
    - /_includes
    - /_layouts
    - 404.html
    - .gitignore
    - .editorconfig
    - .bowerrc
    - LICENSE
    - config.json
    - Gruntfile.js
    - js
    - dist
    - less
    - Makefile
    - README.md
    - _config.yml
    - atom.xml
    - bower.json
    - index.html
    - package.json
  metadata:
    _drafts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "Family Policy"
              value: "Family-policy"
            - name: "Parenting"
              value: "Parenting"
